import { defineConfig } from 'vite';
import sharp from 'sharp';
import { readdir } from 'node:fs/promises';

// Expands <img data-pic="name" ...> into a <picture> with AVIF/WebP/JPG srcsets
// generated by scripts/images.mjs, and adds intrinsic width/height against layout shift.
function pictures() {
  let variants;
  async function load() {
    if (variants) return variants;
    variants = {};
    for (const file of await readdir('public/img')) {
      const m = file.match(/^(.+)-(\d+)\.jpg$/);
      if (!m) continue;
      (variants[m[1]] ||= []).push(Number(m[2]));
    }
    for (const name of Object.keys(variants)) {
      variants[name].sort((a, b) => a - b);
      const meta = await sharp(`public/img/${name}-${variants[name].at(-1)}.jpg`).metadata();
      variants[name].ratio = meta.height / meta.width;
    }
    return variants;
  }
  return {
    name: 'dola-pictures',
    async transformIndexHtml(html) {
      const v = await load();
      return html.replace(/<img data-pic="([\w-]+)"([^>]*)>/g, (_, name, rest) => {
        const ws = v[name];
        if (!ws) throw new Error(`Unknown picture: ${name}`);
        const set = (ext) => ws.map((w) => `/img/${name}-${w}.${ext} ${w}w`).join(', ');
        const sizes = rest.match(/sizes="([^"]+)"/)?.[1] ?? '100vw';
        const attrs = rest.replace(/\s*sizes="[^"]+"/, '');
        const base = ws.find((w) => w >= 800) ?? ws.at(-1);
        const h = Math.round(base * ws.ratio);
        return `<picture><source type="image/avif" srcset="${set('avif')}" sizes="${sizes}"><source type="image/webp" srcset="${set('webp')}" sizes="${sizes}"><img src="/img/${name}-${base}.jpg" srcset="${set('jpg')}" sizes="${sizes}" width="${base}" height="${h}"${attrs}></picture>`;
      });
    },
  };
}

export default defineConfig({
  plugins: [pictures()],
  build: { target: 'es2020' },
});
